configuration:
- Release

platform:
- x64

image:
- Visual Studio 2017

environment:
  PRJ_NAME: AdbWinGui 
  
install:
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- cd %APPVEYOR_BUILD_FOLDER%

##### 
deploy:
- provider: GitHub
  auth_token:
    secure: the-token-is-hidden-on-purpose
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
