configuration:
- Release

platform:
- x64

image:
- Visual Studio 2017
- Visual Studio 2013

environment:         
  PRJ_NAME: AdbWinGui

build_script:
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%

    
    
