configuration:
- Release

platform:
- x64

image:
- Visual Studio 2017
- Visual Studio 2013

environment:         
  PRJ_NAME: AdbWinGui

build_script:
- ps: If ( $env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2013") { $PlatformToolset = "v120" } 
      If ( $env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015") { $PlatformToolset = "v140" } 
      If ( $env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") { $PlatformToolset = "v141" } 
###     
- cmd: echo %APPVEYOR_BUILD_WORKER_IMAGE% %PlatformToolset%

    
    
