configuration:
- Release

platform:
- x86
- x64

image:
- Visual Studio 2015

environment:         
  PRJ_NAME: AdbWinGui

build_script:
- ps: >-
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2013") {
      $PlatformToolset = "v120"
    } elseif ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015") {
      $PlatformToolset = "v140"
    } else {
      $PlatformToolset = "v141"
    }



    & msbuild $PRJ_NAME.vcxproj "/p:platform=$env:platform;configuration=$env:configuration"

    & msbuild $PRJ_NAME.vcxproj "/p:platform=$env:platform;configuration=$env:configuration"
