configuration:
- Release

platform:
- x64

image:
- Visual Studio 2017
- Visual Studio 2013

environment:         
  PRJ_NAME: AdbWinGui

build_script:
    - if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2013") {
      $PlatformToolset = "v120"
    } elseif ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015") {
      $PlatformToolset = "v140"
    } else {
      $PlatformToolset = "v141"
    }  
   
    
   - echo APPVEYOR_BUILD_WORKER_IMAGE
    
    
