configuration:
- Release

platform:
- x64

image:
- Visual Studio 2017

environment:
  PRJ_NAME: AdbWinGui 
  
install:
 - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

##### 
deploy:
- provider: GitHub
  auth_token:
    secure: the-token-is-hidden-on-purpose
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
